feat(home): refresh homepage design
LJSkinner/Uni-Stirling-Grade-Calculator-Website pull request #32
Opened 2023-04-28 21:11 UTC by AndrewMcGuckin

Refreshes the homepage design, updates button id's to enable undergrad modal functionality and uploads main.css to include style changes.

Closes #31

2023-04-28 21:47 UTC, LJSkinner requested changes
Just one small thing in the js file before acceptance.

2023-04-28 21:47 UTC, LJSkinner commented on src/js/undergrad.js
> +const modalCancelBtn = document.getElementById("amCancelBtn");
I don't know if I am fan of these abbreviations. I understand the thought of it being quite long winded but personally I'd actually just prefer something like:
```javascript
const modalDiscardBtn = document.getElementById("editModalDiscardBtn")
const modalCancelBtn = document.getElementById("addModalCancelBtn")
```
I think the prefixes we have of edit and add are not so long that it makes these too bad in long form.

2023-05-02 13:10 UTC, AndrewMcGuckin commented on src/js/undergrad.js
> +const modalCancelBtn = document.getElementById("amCancelBtn");
This should be resolved in the latest commit 😀

2023-05-02 13:10 UTC, LJSkinner approved these changes

2023-05-02 13:11 UTC, merged